
ALTER TABLE public.partidas
ADD COLUMN IF NOT EXISTS code VARCHAR(6),
ADD COLUMN IF NOT EXISTS host_id UUID,
ADD COLUMN IF NOT EXISTS turn_time INTEGER DEFAULT 60,
ADD COLUMN IF NOT EXISTS map VARCHAR(255) DEFAULT 'arrakis';

ALTER TABLE public.player_estado
ADD COLUMN IF NOT EXISTS house VARCHAR(50);
